# Generated by Django 6.0 on 2025-12-22 23:37

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_exactly_as_in_openreview', models.BooleanField(default=False)),
                ('paper_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('upload_paper', models.FileField(upload_to='uploads/', validators=[upload.models.validate_pdf_20mb])),
                ('type', models.CharField(choices=[('Paper', 'Paper'), ('Position Paper', 'Position Paper')])),
                ('confirm_styles', models.BooleanField(default=False)),
                ('confirm_title', models.BooleanField(default=False)),
                ('confirm_9_pages', models.BooleanField(default=False)),
                ('confirm_appendices', models.BooleanField(default=False)),
                ('confirm_abstract', models.BooleanField(default=False)),
                ('confirm_title_case', models.BooleanField(default=False)),
                ('confirm_macos_preview', models.BooleanField(default=False)),
                ('confirm_type_3_fonts', models.BooleanField(default=False)),
            ],
        ),
    ]
