# Generated by Django 6.0 on 2025-12-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='id',
        ),
        migrations.AddField(
            model_name='upload',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
