# Generated by Django 6.0 on 2025-12-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_upload_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
